// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo9cLyop2egwsby5Fgf-Pa9XBwQN_GlxM',
    appId: '1:451247140482:web:6c7040bbce4517836f4e9b',
    messagingSenderId: '451247140482',
    projectId: 'bacain-dbecb',
    authDomain: 'bacain-dbecb.firebaseapp.com',
    storageBucket: 'bacain-dbecb.appspot.com',
    measurementId: 'G-29ZNLNKZW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS3uoyxOuPtGei6zB2gYcw2SIxVM5WF5Y',
    appId: '1:451247140482:android:ce26c643a0d3849c6f4e9b',
    messagingSenderId: '451247140482',
    projectId: 'bacain-dbecb',
    storageBucket: 'bacain-dbecb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFAG3aY-QtdzHmFNhQRsnVBLbcEHeDsUY',
    appId: '1:451247140482:ios:be4347dd920c65c46f4e9b',
    messagingSenderId: '451247140482',
    projectId: 'bacain-dbecb',
    storageBucket: 'bacain-dbecb.appspot.com',
    iosClientId: '451247140482-rbc2ch46qh8npmlqcu4man8q44hcrb5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.bacain',
  );
}
